default_language_version:
  python: /Users/hurley/.pyenv/shims/python
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: make-lint
        name: Run Makefile lint
        entry: make lint
        language: system
