---
dist: trusty
sudo: required
language: ruby

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -qq -y shellcheck

install:
  - gem install mdl

script:
  - ./test.sh

notifications:
  irc:
    channels:
      - "chat.freenode.net##phatypus"
    template:
      - "(%{repository_name}) %{build_number}: %{branch}@%{commit} %{author} -> %{message} %{build_url}"
    use_notice: true
