add_newline = true

format = """
$shell\
$time\
$git_branch\
$git_commit\
$git_state\
$git_status\
${custom.pyenv}\
$terraform\
$aws\
$directory\
$line_break\
$character"""

[shell]
disabled = true
bash_indicator = 'b'
zsh_indicator = 'z'
unknown_indicator = '?'
style = 'cyan bold'
format = '[$indicator]($style) [|](bright-black) '

[time]
disabled = true
time_format = '%T'
style = "bright-black"
format = "[$time]($style) [|](bright-black) "

[git_branch]
symbol = ''
ignore_branches = []
style = 'green'
format = '[${symbol}$branch(:$remote_branch)]($style) '

[git_commit]
style = 'red'
format = '[$hash$tag]($style)'

[git_state]
style = 'white'
format = ' [$state( $progress_current/$progress_total)]($style)'

[git_status]
disabled = false
conflicted = '[⚑](bold red)'
deleted = 'x'
modified = '*'
up_to_date = '[=](white)'
style = 'red'
format = '[$all_status$ahead_behind]($style) [|](bright-black) '

[python]
disabled = false
symbol = ''
style = 'yellow'
format = '[${symbol}($virtualenv)]($style) [|](bright-black) '

[aws]
disabled = false
symbol = ''
style = 'red'
format = '[${symbol}($profile )(${region})]($style) [|](bright-black) '

[directory]
disabled = false
read_only = ' 🔒'
truncation_length = 0
truncation_symbol = ''
truncate_to_repo = false
style = 'white'
format= '[$path]($style)[$read_only]($read_only_style)'

[line_break]
disabled = false

[character]
success_symbol = '[\$](white)'
error_symbol = '[\$](bold red)'

[custom.pyenv]
command = "pyenv version-name"
when = 'test "$(pyenv version-name)" != "default"'
style = 'yellow'
format = '[$output]($style) [|](bright-black) '
