name: lint
on: push

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get install -qq -y shellcheck yamllint
      - name: Run linters
        run: |
          ./lint.sh
